### ISSUE TITLE
기본 프로젝트 파일 내용분석

### ISSUE THREAD

**Issue by cbk1411** [nodeHero/mandalart#1]
- pakages.json
  - 각 설치요소의 역할
- /bin/www
  - 각 라인의 의미
- app.js
  - 각 라인의 의미
- express.js 개념정리

**Comment by cbk1411** [comment]
분석 결과는 정리해서 wiki에 넣음 좋을듯?

**Comment by ParkYoungWoong** [comment]
오키오키
