### ISSUE TITLE
.jade vs .ejs

### ISSUE THREAD

**Issue by ParkYoungWoong** [nodeHero/mandalart#2]
![json_ejs](https://cloud.githubusercontent.com/assets/16679082/13243095/f7517d02-da3e-11e5-913f-b24a562123b9.jpg)

- **.jade** 란?
    - node.js 의 뷰 템플릿엔진으로 express에서 사용할 수 있다. 
    - HTML 보다 심플한 형태로 마크업을 작성하며 자동으로 HTML 을 생성/처리 한다.
- **.ejs** 란?
    - Embedded Javascript
    - node.js 의 뷰 템플릿엔진으로 express에서 사용할 수 있다. 
    - HTML 을 그대로 사용할 수 있다.

> 아직 국내 퍼블리싱 환경에서는 ejs를 쓰는게 좋다고 하던데... 
무슨 소리인가 했더니 HTML을 그대로 사용할 수 있기 때문인 듯!
jade 작성이 심플하니 좋아보이는데... 차차 배우는게 좋겠지?
일단 나는 ejs를 써야 알아볼 수 있을 듯... 즉 템플릿은 **EJS**로!!

**Comment by BK-Choi** [comment]
오호 나이스!
일다 두가지 구현한 샘플을 보고 결정해보자고
아마 ejs로 갈 것 같지만, 업계에서 뭘 쓰는지도 중요하니까네

**Comment by BK-Choi** [comment]
그럼 둘 다 ejs에 찬성이니 이슈는 닫습니당.
