### ISSUE TITLE
css, js merge

### ISSUE THREAD

**Issue by ParkYoungWoong** [nodeHero/mandalart#7]
### common 파일들 src 폴더에서 관리하기
- reset.css 어떻게 사용할 것인지 고민하기
- js 파일들 merge 하기
- 그런트 or 걸프 사용해보기!(공부하기!)

**Comment by BK-Choi** [comment]
- reset.css는 reset.less로 변환하여 `/app/less/common/`으로 이동
- gulp설정
  - 커밋 리뷰에 자세히 설명하겠음
  - README.md에 프로젝트 개발방법 기록하겠음
  - `local` task를 실행하면 `watch` task를 실행 후 서버가 켜짐
  - `watch` task는 `app/js/sources/**/*.js`,  `app/less/**/*.less` 변경시 `jsmerge`,`lessmerge` task를 수행

**Comment by BK-Choi** [comment]
파일 합치기, 자동새로고침, 폴더구조 변경 완료.
관련내용 README.md에 적용하고 이슈 닫겠음!
